# Render Web Service Configuration
services:
  - type: web
    name: iris-backend
    env: python
    plan: free
    buildCommand: uv sync
    startCommand: uv run python -m uvicorn core.run:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.11
    rootDir: backend
    healthCheckPath: /health
    envVars:
      - key: ENV_MODE
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11